"""
Binary cross-entropy loss with class weighting.

ASVspoof2019 LA's training set has far more spoof clips than bonafide ones
(spoof is generated by 6 different attack algorithms). Since label 1 = spoof
(majority) and label 0 = bonafide (minority), BCEWithLogitsLoss's pos_weight
should come out < 1 -- that down-weights the already-common spoof class
relative to bonafide, which is the standard way to rebalance this without
oversampling or discarding data (the decision we locked in earlier).
"""

import torch
import torch.nn as nn

from datasets_src.dataset import parse_protocol, LABEL_MAP


def compute_pos_weight(split="train"):
    """pos_weight = num_negative / num_positive = num_bonafide / num_spoof."""
    entries = parse_protocol(split)
    labels = [LABEL_MAP[label] for _filename, _attack_id, label in entries]
    num_spoof = sum(labels)                 # label 1
    num_bonafide = len(labels) - num_spoof  # label 0

    if num_spoof == 0:
        raise ValueError(f"No spoof examples found in '{split}' protocol -- check parsing.")

    pos_weight = num_bonafide / num_spoof
    print(f"[{split}] bonafide={num_bonafide}, spoof={num_spoof}, pos_weight={pos_weight:.4f}")
    return pos_weight


def build_criterion(pos_weight_value, device):
    pos_weight_tensor = torch.tensor(pos_weight_value, dtype=torch.float32, device=device)
    return nn.BCEWithLogitsLoss(pos_weight=pos_weight_tensor)
